### ISSUE TITLE
dm-cli 1.2.0 won't use dm-core 1.2.0

### ISSUE THREAD

**Issue by L2G** [datamapper/dm-cli#1]
```

[larry:~]$ dm
/Library/Ruby/Site/1.8/rubygems/dependency.rb:247:in `to_specs': Could not find dm-core (= 1.0.0) amongst [ZenTest-4.6.2, addressable-2.2.6, allison-2.0.3, bcrypt-ruby-3.0.1, builder-3.0.0, bundler-1.0.21, columnize-0.3.6, commonwatir-1.9.2, data_objects-0.10.7, datamapper-1.2.0, diff-lcs-1.1.3, dm-aggregates-1.2.0, dm-cli-1.2.0, dm-constraints-1.2.0, dm-core-1.2.0, dm-do-adapter-1.2.0, dm-migrations-1.2.0, dm-postgres-adapter-1.2.0, dm-serializer-1.2.1, dm-sqlite-adapter-1.2.0, dm-timestamps-1.2.0, dm-transactions-1.2.0, dm-types-1.2.1, dm-validations-1.2.0, do_postgres-0.10.7, do_sqlite3-0.10.7, fastercsv-1.5.4, ffi-1.0.11, firewatir-1.9.2, git-1.2.5, hoe-2.10.0, jeweler-1.6.4, json-1.6.3, json_pure-1.6.3, linecache-0.46, msgpack-0.4.6, multi_json-1.0.4, rack-1.3.5, rack-protection-1.1.4, rake-0.9.2.2, rake-0.9.2, rb-appscript-0.6.1, rbtrace-0.3.17, rbx-require-relative-0.0.5, rdiscount-1.6.8, rdoc-3.12, rspec-2.7.0, rspec-1.3.2, rspec-core-2.7.1, rspec-expectations-2.7.0, rspec-mocks-2.7.0, ruby-debug-0.10.4, ruby-debug-base-0.10.4, rubyforge-2.0.4, rubygems-update-1.8.5, s4t-utils-1.0.4, safariwatir-0.4.0, sinatra-1.3.1, stringex-1.3.0, syntax-1.0.0, test-spec-0.10.0, tilt-1.3.3, trollop-1.16.2, user-choices-1.1.6.1, uuidtools-2.1.2, virtus-0.0.10, xml-simple-1.1.0, yard-0.7.4] (Gem::LoadError)
    from /Library/Ruby/Site/1.8/rubygems/dependency.rb:256:in `to_spec'
    from /Library/Ruby/Site/1.8/rubygems.rb:1182:in `gem'
    from /Library/Ruby/Gems/1.8/gems/dm-cli-1.2.0/bin/dm:6
    from /usr/bin/dm:19:in `load'
    from /usr/bin/dm:19
```

**Comment by rojotek** [comment]
the offending lines of code are in the dm file in bin.  It has specific calls to gem dm-core and dm-cli with versions set to 1.0.0

I would have thought that this wouldn't be required at all and that the gem packaging would already result in the appropriate gems being loaded.
